name: docker build

# 1. Trigger
on:
  push:
    branches:
      - workflow_test
    tags:
      - "v*.*.*"

env:
  GITHUB_REGISTRY: ghcr.io
  GITHUB_IMAGE_NAME: ${{ github.repository }}
  DOCKER_HUB_IMAGE_NAME: ${{ github.event.repository.name }}
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  docker:
    runs-on: ubuntu-20.04
    if: ${{ env.DOCKERHUB_TOKEN != null }}
    steps:
      # 2. setup variables
      - uses: FranzDiebold/github-env-vars-action@v2
      - name: Get current date
        id: date
        run: echo "::set-output name=today::$(date +'%Y%m%d')"
      # 3. Checkout code
      - name: Checkout
        uses: actions/checkout@v2
      # 4. Login DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # 5. setup buildx
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      # cache
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      # 6. Build and Push
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          # 7. nameing
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_HUB_IMAGE_NAME }}:${{ steps.date.outputs.today }}
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_HUB_IMAGE_NAME }}:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  ghcr:
    runs-on: ubuntu-20.04
    steps:
      # 2. setup variables
      - uses: FranzDiebold/github-env-vars-action@v2
      - name: Get current date
        id: date
        run: echo "::set-output name=today::$(date +'%Y%m%d')"
      # 3. Checkout code
      - name: Checkout
        uses: actions/checkout@v2
      # 4. Login Github
      - name: Login to Github Container Registory
        uses: docker/login-action@v1
        with:
          registry: ${{ env.GITHUB_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        env:
          OWNER: ${{ github.repository_owner }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.GITHUB_REGISTRY }}/${{ env.GITHUB_IMAGE_NAME }}

      # 5. setup buildx
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      # cache
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
